# config/zones.yaml
zones:
  inside:       { zone_id: "1", sli: "2B" }  # main can use NET
  front_patio:  { zone_id: "2", sli: "03" }  # AUX (or "05" = PC)
  back_patio:   { zone_id: "3", sli: "03" }
